baseURL = "https://otaldoandre.github.io/"
languageCode = "pt-br"
title = "André"

theme = "PaperMod"

summaryLength = 125
enableGitInfo = true

[params]
  ShowLastMod = true
  ShowSummary = true
  defaultTheme = "light"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowShareButtons = false
  disableSpecial1stPost = true
  [params.homeInfoParams]
    Title = "Filosofia, Teologia e (quem sabe) Computação."
    Content = "Reflexões de alguém interessado em Filosofia, Teologia, Tecnologia e Desenvolvimento Pessoal desde a adolescência."
[menus]

  [[menus.main]]
    name = "Sobre"
    pageRef = "/about"
    weight = 2
  [[menus.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 3


[taxonomies]
  tag = "tags"